-- Criar o database
CREATE DATABASE compras_db;

-- Criar o SCHEMA no banco
CREATE SCHEMA IF NOT EXISTS LISTA_COMPRAS;

-- Criação das Tabelas
CREATE TABLE LISTA_COMPRAS.LISTA (
    ID_LISTA SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_CRIACAO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    EXCLUIDO INT2 DEFAULT(0)

    --PRIMARY KEY (ID_LISTA)
);


CREATE TABLE LISTA_COMPRAS.TIPO (
    ID_TIPO SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EXCLUIDO INT2 DEFAULT(0)

    --PRIMARY KEY (ID_TIPO)
);


CREATE TABLE LISTA_COMPRAS.ITEM (
    ID_ITEM SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    MEDIDA VARCHAR(20) NOT NULL, -- 20 KG
    EXCLUIDO INT2 DEFAULT(0),
    FK_ID_TIPO INT8 NOT NULL,

    --PRIMARY KEY (ID_ITEM),
    FOREIGN KEY (FK_ID_TIPO) REFERENCES LISTA_COMPRAS.TIPO(ID_TIPO)
);


CREATE TABLE LISTA_COMPRAS.ITEM_COMPRA (
    ID_ITEM_COMPRA SERIAL PRIMARY KEY,
    VALOR INT8 NOT NULL,
    QUANTIDADE INT8 NOT NULL,
    SELECIONADO INT2 DEFAULT(0),
    FK_ID_ITEM INT8 NOT NULL,
    FK_ID_LISTA INT8 NOT NULL,

    --PRIMARY KEY (ID_ITEM_COMPRA),
    FOREIGN KEY (FK_ID_ITEM) REFERENCES LISTA_COMPRAS.ITEM(ID_ITEM),
    FOREIGN KEY (FK_ID_LISTA) REFERENCES LISTA_COMPRAS.LISTA(ID_LISTA)
);
